In [1]:
import numpy as np

In [4]:
#1dimentional array
arr1 = np.array([5, 6, 8, 3, 10, 4])
 
#2dimentional array
arr2 = np.array([[1, 3, 5],[2, 4, 6]])

In [5]:
arr1


array([ 5,  6,  8,  3, 10,  4])

In [6]:
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
arr1.shape

(6,)

In [8]:
arr1.ndim


1

In [9]:
arr1.size

6

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arr2.shape


(2, 3)

In [13]:
arr2.size

6

In [14]:
arr2.ndim

2

In [16]:
arr2.dtype

dtype('int32')

In [19]:
arr3 = np.ones((5,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
arr4 = np.zeros((3,3,5))
arr4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
arr5 = np.random.randint(0, 10, (7,2))
arr5

array([[4, 0],
       [6, 1],
       [8, 5],
       [6, 1],
       [6, 5],
       [6, 7],
       [0, 7]])

In [31]:
arr6 = np.random.rand(3,5)
arr6

array([[0.5057191 , 0.45184955, 0.39197108, 0.33832726, 0.16039732],
       [0.76508618, 0.21523774, 0.69363554, 0.5278035 , 0.53102742],
       [0.21940353, 0.93003907, 0.64975559, 0.2574992 , 0.07848726]])

In [33]:
arr7 = np.random.rand(7)
arr7

array([0.44033499, 0.97871184, 0.93782799, 0.46237612, 0.0895734 ,
       0.49344966, 0.26369083])

In [38]:
#set random seed to 42
np.random.seed(42)

#random array of numbers between 0 and 10 of size(4,6)
arr8 = np.random.rand(4,6)
arr8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [40]:
np.random.seed(42)
arr8 = np.random.rand(4,6)
arr8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [41]:
print(arr8[0][0])

0.3745401188473625


In [42]:
fir = arr8[0]
sec = arr8[1]
print(fir,"\n",sec)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452] 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [45]:
#get first two values of the first two rows of the latest array
print(arr8[0][0], "\n", arr8[1][0])

0.3745401188473625 
 0.05808361216819946


In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
arr9 = np.random.randint(0,10,(3,5), np.int64)
arr10 = np.ones((3,5), dtype = np.int64) 

In [50]:
#add arr9 and arr10
arr11 = arr9 + arr10
arr11

array([[ 6,  6, 10,  4,  6],
       [ 2, 10,  2, 10,  4],
       [ 8,  7,  9,  8,  5]], dtype=int64)

In [53]:
arr12 = np.ones((5,3), dtype = np.int64)
arr12

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [54]:
arr13 = arr11 + arr12

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [56]:
arr13 = arr11 + np.transpose(12)
arr13

array([[18, 18, 22, 16, 18],
       [14, 22, 14, 22, 16],
       [20, 19, 21, 20, 17]], dtype=int64)

In [57]:
arr13**2

array([[324, 324, 484, 256, 324],
       [196, 484, 196, 484, 256],
       [400, 361, 441, 400, 289]], dtype=int64)

In [58]:
np.power(arr13,2)

array([[324, 324, 484, 256, 324],
       [196, 484, 196, 484, 256],
       [400, 361, 441, 400, 289]], dtype=int64)

In [59]:
print(np.mean(arr13),"\n",np.max(arr13),"\n",np.min(arr13),"\n",np.std(arr13),"\n",np.var(arr13))

18.466666666666665 
 22 
 14 
 2.6297443897754693 
 6.915555555555557


In [61]:
arr14 = np.random.randint(0,10,(3,3), np.int64)
arr15 = np.random.randint(0,10,(3,2), np.int64)
print(arr14, "\n", arr15)

[[0 7 2]
 [2 0 4]
 [9 6 9]] 
 [[8 6]
 [8 7]
 [1 0]]


In [62]:
dot_product = np.dot(arr14,arr15)
dot_product

array([[ 58,  49],
       [ 20,  12],
       [129,  96]], dtype=int64)

In [63]:
arr16 = np.random.randint(0,10,(4,3), np.int64)
arr17 = np.random.randint(0,10,(4,3), np.int64)
print(arr16, "\n", arr17)

[[6 6 7]
 [4 2 7]
 [5 2 0]
 [2 4 2]] 
 [[0 4 9]
 [6 6 8]
 [9 9 2]
 [6 0 3]]


In [65]:
hadmard = np.multiply(arr16,arr17)
hadmard

array([[ 0, 24, 63],
       [24, 12, 56],
       [45, 18,  0],
       [12,  0,  6]], dtype=int64)

In [66]:
dot1 = np.dot(arr16,arr17)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [70]:
dota = np.dot(arr16, np.transpose(arr17))
dota

array([[ 87, 128, 122,  57],
       [ 71,  92,  68,  45],
       [  8,  42,  63,  30],
       [ 34,  52,  58,  18]], dtype=int64)

In [71]:
arr18 = np.random.randint(0,10,(6,4), np.int64)
arr19 = np.random.randint(0,10,(6,4), np.int64)
print(arr18, "\n", arr19)

[[3 4 6 6]
 [3 6 2 5]
 [1 9 8 4]
 [5 3 9 6]
 [8 6 0 0]
 [8 8 3 8]] 
 [[2 6 5 7]
 [8 4 0 2]
 [9 7 5 7]
 [8 3 0 0]
 [9 3 6 1]
 [2 0 4 0]]


In [72]:
print(arr18 > arr19)
print(arr18 <= arr19)
print(arr18 == arr19)

[[ True False  True False]
 [False  True  True  True]
 [False  True  True False]
 [False False  True  True]
 [False  True False False]
 [ True  True False  True]]
[[False  True False  True]
 [ True False False False]
 [ True False False  True]
 [ True  True False False]
 [ True False  True  True]
 [False False  True False]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False  True False False]
 [False False False False]
 [False False False False]]


In [73]:
np.sort(arr18)

array([[3, 4, 6, 6],
       [2, 3, 5, 6],
       [1, 4, 8, 9],
       [3, 5, 6, 9],
       [0, 0, 6, 8],
       [3, 8, 8, 8]], dtype=int64)

In [74]:
np.argsort(arr18)

array([[0, 1, 2, 3],
       [2, 0, 3, 1],
       [0, 3, 2, 1],
       [1, 0, 3, 2],
       [2, 3, 1, 0],
       [2, 0, 1, 3]], dtype=int32)

In [75]:
np.argmax(arr19)

8

In [77]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [78]:
np.argmax(arr19,axis = 1)

array([3, 0, 0, 0, 0, 2], dtype=int32)

In [79]:
np.argmin(arr19,axis = 0)

array([0, 5, 1, 3], dtype=int32)